### ISSUE TITLE
redirect no-www to www

### ISSUE THREAD

**Issue by Deeonix** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#112]
Is there a way to get a redirect from http(s)://example.com to https://www.example.com?

**Comment by khalilgharbaoui** [comment]
@Deeonix what was your solution for this? would be helpful if you share maybe

**Comment by evertramos** [comment]
add it to the hosts name in the compose file of your site.

**Comment by khalilgharbaoui** [comment]
I see but that is not possible for my config I need to be globally.
Anything www should go is its non-www equivalent.

Because the domain names are dynamically generated and in the docker-compose file I have:

```
      VIRTUAL_HOST:  'domain.com, *.domain.com'
      VIRTUAL_PORT:  5000
      CERT_NAME:  domain
```
As you can see im using a custom ssl cert.
It works for `sub.domain.com` 
But never for `www.sub.domain.com` because thats how wildcards work.

So i need to redirect www to non-www on a global nginx level.
I read that it's also possible to add another nginx in front of the app itself that does this kind of redirect but that over complicates things. i feel this should be simple. as it's a general rule for all applications running on the same server.

Is it possible to do this on a global level?

**Comment by evertramos** [comment]
don't change nginx.tmpl... get a host config level and do your own settings in domain level.

**Comment by evertramos** [comment]
there is a pull request for that on the way

https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/pull/229
