### ISSUE TITLE
How about differences between JrCs?

### ISSUE THREAD

**Issue by gustawdaniel** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#153]
There is package:

> https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion

And this package with `docker-compose-letsencrypt-nginx-proxy-companion`. But first one have section in documentation about usage with docker.

> https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/blob/master/docs/Docker-Compose.md

I see that in `JrCs` there is no `network` key in configuration used. Can you explain more about similarities and differences? Was this package inspired by `JrCs`, has any advantage over them? Which one is more advanced? I looking for comprehensive comparison that can be useful for other.

**Comment by evertramos** [comment]
Hello @gustawdaniel,

It will all get the job done! I put this together for myself with docker-compose version 3 and using it for about 4 years in production servers. So it depends on what you want and how you want it... 

I am working in a new script for a while now and should be ready by end of the year... really a side work on that. 

My way of thinking is always make things easy of use and understanding.

The network is an option to split services into different subnets... but you can choose not to use it. It was my demand because in server I have many clients and all of them has it´s own docker subnet.

Hope my comments will help you decide which way to go!
