### ISSUE TITLE
Custom nginx config timeout.conf stopped working.

### ISSUE THREAD

**Issue by bollerdominik** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#158]
I used to have following timeout.conf

```
http {
     fastcgi_read_timeout 300s;
     proxy_read_timeout 300s;
}
```

For many months my docker-compose-letsencrypt-nginx-proxy-companion setup worked worked flawlessly. Yesterday I noticed that all calls to the server where timing out. Checking the nginx container logs I saw a bunch of 

> [emerg] 1#1: "http" directive is not allowed here in /etc/nginx

Kindly asking for suggestions on what went wrong and on how to apply my 300s timeout again

**Comment by evertramos** [comment]
Hello @bollerdominik,

Did you update recently? 

We must check the nginx template to see if there was any change in @jwilder repo... but I couldn´t notice any change in the last few days on that subject.

**Comment by bollerdominik** [comment]
No I only updated (ran start.sh again) after discovering the issue. I had to remove the timout.conf to make it run again. 

My server was running untouched for at least a month before it suddenly stopped accepting connections and failed with the error shown above.

Do yo have any suggestion how I can set the nginx timeout again?

**Comment by evertramos** [comment]
Hello @bollerdominik,

Thanks for you reply. I think I know what's wrong...

The nginx *proxy_read_timeout* should be accepted on http context... so the issue is that you are setting the **http {}** context, which is already present in the nginx.conf.

Please, try to set your timeout.conf file only with:

```bash
fastcgi_read_timeout 300s;
proxy_read_timeout 300s;
```

Make sure the folder conf.d is being loaded by you compose file, our current settings already load it and try again.

Hope it helps!
