### ISSUE TITLE
AcmeV1 did not works anymore 

### ISSUE THREAD

**Issue by RonPimplebut** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#180]
# Error description:
only http works I am unable to setup a new certificate

# Steps to reproduce
1. clone this repo and cd into it 
2. edit the .env as you wish
3. type ./start.sh
4. start your website container

# Expected result
working https website on my domain name

# Error result
Attaching to nginx-letsencrypt, nginx-gen, nginx-web
nginx-letsencrypt    | Info: Custom Diffie-Hellman group found, generation skipped.
nginx-letsencrypt    | 2019/12/27 02:55:16 Generated '/app/letsencrypt_service_data' from 3 containers
nginx-letsencrypt    | 2019/12/27 02:55:16 Running '/app/signal_le_service'
nginx-letsencrypt    | 2019/12/27 02:55:16 Watching docker events
nginx-letsencrypt    | 2019/12/27 02:55:16 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/signal_le_service'
nginx-letsencrypt    | Sleep for 3600s
nginx-letsencrypt    | Sleep for 3600s
nginx-letsencrypt    | Sleep for 3600s
nginx-letsencrypt    | 2019/12/27 05:47:51 Received event start for container 8d84338a0668
nginx-letsencrypt    | 2019/12/27 05:47:53 Received event start for container b8cc3b71dab6
nginx-letsencrypt    | 2019/12/27 05:48:08 Debounce minTimer fired
nginx-letsencrypt    | 2019/12/27 05:48:08 Generated '/app/letsencrypt_service_data' from 5 containers
nginx-letsencrypt    | 2019/12/27 05:48:08 Running '/app/signal_le_service'
nginx-letsencrypt    | /etc/nginx/certs/info-data.cf /app
nginx-letsencrypt    | Reloading nginx docker-gen (using separate container nginx-gen)...
nginx-letsencrypt    | Reloading nginx (using separate container cee2ecd144dee766a406f07f567bb78453a6edf5d33aabb2ad99e4e379a6891d)...
nginx-letsencrypt    | Creating/renewal info-data.cf certificates... (mydomain.com www.mydomain.com)
nginx-letsencrypt    | 2019-12-27 05:48:10,917:INFO:simp_le:1382: Generating new account key
nginx-letsencrypt    | ACME server returned an error: urn:acme:error:unauthorized :: The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

# Comments

I am looking for an alternative anybody have a idea ? 
Thanks

**Comment by fracz** [comment]
I have received a notification from LE today, too.

> According to our records, the software client you're using to get Let's 
Encrypt TLS/SSL certificates issued or renewed at least one HTTPS certificate 
in the past two weeks using the ACMEv1 protocol. Your client's IP address was:
> Beginning June 1, 2020, we will stop allowing new domains to validate using 
the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before 
then, or certificate issuance will fail. For most people, simply upgrading to 
the latest version of your existing client will suffice. You can view the 
client list at: https://letsencrypt.org/docs/client-options

So... what part of the configuration should we upgrade?

**Comment by pieroit** [comment]
Same question here!

**Comment by fracz** [comment]
It appears that

```
git pull && ./start.sh
```

solves the problem.

**Comment by pgassmann** [comment]
In my case there was a domain that could not be verified.

Update containers to the latest version:

```
docker-compose pull
docker-compose up -d
```

**Comment by evertramos** [comment]
Hello Everyone,

You could set your domain in CloudFlare and set the certificate by this service for free. So you will not need the Let Encrypt anymore... but the communication between the CloudFlare network and your server will not be encrypted. You might set an local certificate with cloudflare or even buy their service for that. 

I am migrating to Traefik since a while ago and will post in readme soon enough to set your server with this service that will proxy all connections the same way this repo does today. I am finishing the migration this month and by the next (feb) I should be using Traefik in production, so I will release the proxy after is ready to go.

Thanks for using this proxy and they probably will update it to use Acme v2 but I will rather depend only from Let’s Encrypt and Traefik from now on. 

Best regards,

Evert

**Comment by pgassmann** [comment]
Hi @evertramos ,

what is your reason to migrate to traefik? I also tried traefik as an alternative but found that the performance of nginx is better with a lot of connections, especially when tuning some nginx config (e.g. set `workers` to `auto` instead of `1`)

It already works with ACMEv2 if updated. I hope this project stays alive.

**Comment by evertramos** [comment]
Hello @pgassmann!

We will keep this up and running. Once Simp_le got update and it is working with ACMEv2.

The Traefik as I could test it is nice and could be an option, but for now, since we have a lot of sites and a couple servers running this proxy, we will keep this solution.

Thanks for your kind words.

Cheers!

**Comment by fracz** [comment]
Pulling the newest `jrcs/letsencrypt-nginx-proxy-companion` and restarting the contaiers seems to solve this problem (certificates are being renewed with v2). There is a discussion of how to check it here: https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/614

I think we can close this issue
