### ISSUE TITLE
Help please: BTCPay Server with letsencrypt-nginx-proxy-companion

### ISSUE THREAD

**Issue by maltokyo** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#189]
# Error description:
I am trying to get letsencrypt-nginx-proxy-companion to run complete web interface of BTCPay server docker version, but really struggling.

# Steps to reproduce and all details are here in the below link
https://github.com/btcpayserver/btcpayserver-docker/issues/267

# If anyone has advice for me, please could you share in the issue above, I just wanted to post it here also, as I was not sure where to ask help.

**Comment by evertramos** [comment]
Hello @maltokyo,

1. Is the DNS configured? 

2. You can ping both domain in your server and reply with the correct server ip address?

> If you are using cloudflare you must skip proxy...

And one last tip on that, you will need to make the service work without ssl because the proxy forward the 443 connection to you container normally to port 80, so, this is something you should look at it.

**Comment by maltokyo** [comment]
@evertramos Thank you for your reply!
Yes, DNS is configured.  Here is the result
https://mxtoolbox.com/SuperTool.aspx?action=a%3apay.malpage.com&run=toolpage

And yes, it is running on port 80.

**Comment by maltokyo** [comment]
I solved this, thank you
