### ISSUE TITLE
bind: cannot assign requested address

### ISSUE THREAD

**Issue by Julianoe** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#22]
I just ran the tutorial as it is and it returns this error 

`ERROR: for nginx-web  Cannot start service nginx-web: driver failed programming external connectivity on endpoint nginx-web (b9ecaee261bb113fbb8d93381e8ab68c3a149feb389d8d60a64534aad80ecd54): Error starting userland proxy: listen tcp MYIP:443: bind: cannot assign requested address
`
In the docker-compose.yml i commented out the part that mentions the IP and replaced with just 

```
   ports:
#      - "${IP}:80:80"
#      - "${IP}:443:443"
       - "80:80"
       - "443:443"
```

I ran the test file and it works. But just for my culture and better understanding, what is the reason of the error?

EDIT : it seems it simply does not work :/ (see related issue)

**Comment by evertramos** [comment]
This happens because you use a wront ip address. Are you in a public IP? If you set your correct external IP address it will work.

**Comment by Julianoe** [comment]
The IP from my dedicated server is the following : it's the one i used and that returned this error
51.15.215.181

**Comment by evertramos** [comment]
Are you sure you set up it correctly? Because this error is pretty much for this reason, and it's a docker function that generate the binding addres, which checks your network addres. So, or this address is not set correctly in you .env file or you do not have this ip settled for this machine. Please check.

**Comment by evertramos** [comment]
@Julianoe,

Could you please past your `ifconfig` showing your external network interface (normally eth0)?

I believe that your server uses internal IP address, like AWS had some kind of proxy, which in the server has only local address.

So, you get your eth0 or virtual interface IP address and use it instead of the external IP address.

Please try and let me know.

**Comment by Julianoe** [comment]
Yes you were right!

My server provider (scaleway) indeed attributes both internal and external addresses. With external it did not work but once replaced by internal address it worked without any error!
