### ISSUE TITLE
Support for fastcgi.conf

### ISSUE THREAD

**Issue by xgenvn** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#24]
# Error description:
If specify **VIRTUAL_PROTO=fastcgi,** nginx-web hang due to **fastcgi.conf** not found

# Steps to reproduce
Add **VIRTUAL_PROTO=fastcgi** to environment

# Expected result
- nginx-web support fastcgi mode
- nginx-web not hang

# Error result
- nginx-web hang

# Comments
Can we have a proper support for fastcgi mode?
The template for nginx this repo is using (nginx-proxy) already support it with proper fastcgi file under /etc/nginx.
Actually, the file comes with the nginx image is fastcgi_params.

I can commit a patch to replace the **include fastcgi.conf** line by **include fastcgi_params**. Just not quite sure that's the correct way to solve this problem.

**Comment by evertramos** [comment]
Hello @xgenvn,

I have teste and it work smothly on my side.

The `nginx-gen` keeps restarting because when you start this environment with a default.conf already set it conflicts with the container file generation. So please REMOVE you old `/conf.d` folder and run `./start.sh` again.

Please check this [FastCGI](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion/blob/fastcgi/start.sh) branch.

I do not use it in production yet, but it seems to work.

Please confirm.

**Comment by evertramos** [comment]
Since I had not reply... I will assume you got it working!

**Comment by perarg** [comment]
Sorry to open again but when FastCGI is used, it should change the `include fastcgi.conf` to `include fastcgi_params` in nginx.tmpl file.

**Comment by evertramos** [comment]
@perarg This is something done by the proxy... this repo only get things together... and as I do not use the we had no reply I stopped developing this branch. Sorry.. did you make it work? Could you share some code? If so please make a pull request to fastcgi branch. Thanks!

**Comment by DaniSchenk** [comment]
this bug seems to be solved by this PR https://github.com/jwilder/nginx-proxy/pull/1116
it's not merged though
