### ISSUE TITLE
How to add customized options to the config files?

### ISSUE THREAD

**Issue by xfchen** [evertramos/docker-compose-letsencrypt-nginx-proxy-companion#32]
So I was going to reverse proxy Emby (a media server), which needs some more options to work. 

     location / {
        proxy_pass http://192.168.10.10:8096;  

		proxy_set_header Range $http_range;
		proxy_set_header If-Range $http_if_range;
		proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        #Next three lines allow websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
		}

I tried to add these options manually to the default.conf but they got wiped automatically. Is there an alternative way to do this?

**Comment by evertramos** [comment]
@xfchen the default.conf is generated by the docker-gen container developed by @jwilder. You probably would have to adapat the nginx.tmpl file to your needs. What I recommend if you really (really!) know what you are doing. Otherwise check if the default set up works and find out why it´s not working maybe you cound find a way around besides working your own nginx.conf.

**Comment by ThomasWoerdeman** [comment]
Did you find out how to do it?

**Comment by ponschab** [comment]
If someone stumbles over how to do this is described here:
https://github.com/nginx-proxy/nginx-proxy#per-virtual_host
